In [1]:
import pandas as pd;

In [3]:
bangaluru = pd.read_csv('/content/Bengaluru_House_Data.csv');

In [4]:
print("Missing data before imputation:")
print(bangaluru.isnull().sum())

Missing data before imputation:
area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [5]:
most_frequent_location = bangaluru['location'].mode()[0]
bangaluru['location'].fillna(most_frequent_location, inplace=True)

# For 'size': Fill missing values with the most frequent value (mode)
most_frequent_size = bangaluru['size'].mode()[0]
bangaluru['size'].fillna(most_frequent_size, inplace=True)

# For 'society': Fill missing values with the most frequent value (mode)
most_frequent_society = bangaluru['society'].mode()[0]
bangaluru['society'].fillna(most_frequent_society, inplace=True)

# For 'bath': Fill missing values with the median (numerical column)
median_bath = bangaluru['bath'].mode()[0]
bangaluru['bath'].fillna(median_bath, inplace=True)

# For 'balcony': Fill missing values with the median (numerical column)
median_balcony = bangaluru['balcony'].mode()[0]
bangaluru['balcony'].fillna(median_balcony, inplace=True)

<ipython-input-5-907d89f37e21>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bangaluru['location'].fillna(most_frequent_location, inplace=True)
<ipython-input-5-907d89f37e21>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bangaluru['size'].fillna(most_frequent_size, inplace=True)
<ipython-input-5-907d89f37e21>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bangaluru['society'].fillna(most_frequent_society, inplace=True)
<ipython-input-5-907d89f37e21>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bangaluru['bath'].fillna(median_bath, inplace=True)
<ipython-input-5-907d89f37e21>:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bangaluru['balcony'].fillna(median_balcony, inplace=True)

In [6]:
print("\nMissing data after imputation:")
print(bangaluru.isnull().sum())

Missing data after imputation:
area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64